### ISSUE TITLE
[1.16.1] World Gen Issues

### ISSUE THREAD

**Issue by BedrockLegends** [waylanderou/almost-all-the-ores#11]
With this option set to true 
	#Should Nether be cleared of all ore generation from vanilla and other mods.
	clearNether = true

Ores are still spawning, Like Nether Gold Ore for example
![2020-06-28_15 27 37](https://user-images.githubusercontent.com/48525410/85957549-eabe8500-b953-11ea-9cb1-11ad1393b8b7.png)

**Comment by waylanderou** [comment]
I did not know Minecraft now had nether gold ore ! I released a fix for that. Also, nether sulphur and other AatO ores have to be disabled separately under the nether configuration section.

Thank you for reporting this.
