### ISSUE TITLE
Mekanism ore is bypassing Disable Ore gen

### ISSUE THREAD

**Issue by BedrockLegends** [waylanderou/almost-all-the-ores#13]
I have it set in the config to disable all Ore gen, But for some very odd reason Mekanism is still genning

**Comment by waylanderou** [comment]
I thought I had changed this option's description to add "works to some extent", maybe I forgot to change it on all versions of the mod 🤔. I'll try to see if I can change how this work, but I'm not sure I can do anything more.

**Comment by waylanderou** [comment]
I don't think there's a way to make setup jobs after DefferedWorkQueue has finished... The "disabled ore gen" feature only works for mods directly using the common setup event, and to some extent for mods using DeferredWorkQueue, but it's a bit unpredictable so you have to test. In case it doesn't work, you have to use the mod's config file, in your case, mekanism config.
