### ISSUE TITLE
Fractional attempts per chunk rate spawn no ore

### ISSUE THREAD

**Issue by nepphhh** [waylanderou/almost-all-the-ores#14]
Hi there! Fantastic mod. Could be the landmark 1.16 ore control mod, even for only vanilla ores. I'm using it for making big ore clumps in 1.16. 

One behavior I've observed is that if you set attempts per chunk to a values less than 1, it spawns none of that ore. As I don't know whether this is intended behavior, I'm unsure whether this is a bug report or a feature request. If it's a bug report, there you go. If it's a feature request, please make it so there's a chance to attempt ore generation per chunk for values 0<n<1. 

This would permit, for example, keeping diamonds the same rarity but increasing their vein size.

**Comment by waylanderou** [comment]
You can't set values lower than 1, all arguments have to be integers. 
Maybe someone more experienced with modding than I am could mess with the generation system and make it able to take floats. Anyway, I can't do that.
