### ISSUE TITLE
Vanilla Diamonds don't spawn even when enabled in config

### ISSUE THREAD

**Issue by GregoryTheGamer** [waylanderou/almost-all-the-ores#16]
Vanilla Diamond Ore blocks don't spawn at all even when enabling them in config and disabling this mods ores. I am using version 2.0.3.1

**Comment by waylanderou** [comment]
It's a bug actually. Thanks for reporting this. 
I recently added Kimberlite to replace the vanilla diamond ore, but I totally forgot to make an option for people wanting to keep the vanilla diamond ore. Sorry about that, I'll fix it after I'm done with the 1.16.3 update. 🙂

**Comment by GregoryTheGamer** [comment]
Alright, just make sure you backport that fix to 1.15.2 since thats the version I use.

**Comment by waylanderou** [comment]
Outdated version and issue. Vanilla diamond ore spawn works in 3.0.4.2, which is the oldest (and latest for now) supported version.
