### ISSUE TITLE
1.16.4 World gen does not disable

### ISSUE THREAD

**Issue by BedrockLegends** [waylanderou/almost-all-the-ores#18]
Setting 	disableAatoGeneration = true does nothing
![2020-11-22_12 31 26](https://user-images.githubusercontent.com/48525410/99913706-a941c400-2cbe-11eb-9c76-ac74317f065f.png)

**Comment by waylanderou** [comment]
Latest build 3.0.4.2 fixes that. Thanks for the quick bug report. 😊🙂
