### ISSUE TITLE
Tin requires iron pick to harvest

### ISSUE THREAD

**Issue by DancingHoskuld** [waylanderou/almost-all-the-ores#6]
The tin ores require an iron pick to harvest.

I tried setting the tinHarvestLevel to zero in the almostalltheores-common.toml file in the config folder but it did not change anything. Even after exiting and starting a new game.

The value when the mod is first installed is 2 which is iron which makes the bronze age after the iron age :-D

**Comment by waylanderou** [comment]
Did you set _useCustomHarvestLevelValues_ to true in the same section than harvest levels ? I don't remember testing it, but it's the first time people report issues related to custom harvest levels...

**Comment by DancingHoskuld** [comment]
Doh! No it was still false. Sorry about that. Now to try it out.

Yes works fine.
