### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by Raghalin** [waylanderou/almost-all-the-ores#7]
not sure if AATO or HWYLA problem, so I'm posting in both.   when inserted into a 14.4 server they crash during server start.

[crash-2020-04-23_07.21.39-server.txt](https://github.com/waylanderou/almost-all-the-ores/files/4522457/crash-2020-04-23_07.21.39-server.txt)

**Comment by waylanderou** [comment]
I have reproduced the crash and I am now investigating. It seems to be a problem with the registering of my mod's hwyla plugin.

**Comment by waylanderou** [comment]
Fix released !
