### ISSUE TITLE
[1.15.2] Harvest Level Config not working

### ISSUE THREAD

**Issue by TheUntamed** [waylanderou/almost-all-the-ores#8]
Version: 2.0.2.3
Forge: 31.1.43

The harvest level configs have no effect. The harvest level is always the default value no matter what I set in the config file.
I tested this for all lead and tin ore variants. I decreased and increased the value but the ores always required an iron pickaxe.

**Comment by waylanderou** [comment]
This is probably a duplicate of #6 . Maybe the mod shouldn't have this option _useCustomHarvestLevelValues_ and directly change harvest levels... What do you think ?
I don't remember why I added this switch... I think it had something to do with stone age auto values... I'll look into this and try to find a better solution

**Comment by TheUntamed** [comment]
Yeah I missed that option. Interesting.
Because I'm creating my own mod and I also want to change the harvestlevel of my blocks via config, but it doesn't work. That's my try:
https://pastebin.com/AJSGZMJ1
I also looked at your code but I don't get it.

**Comment by waylanderou** [comment]
There is not all your code on pastebin so I can't be sure what you are missing. Uncommenting spec.setConfig(configData) should be a good start. You can ask me on discord waylanderou#1628 or ask on the Forge discord group (#modder-support-115).

**Comment by TheUntamed** [comment]
That did the trick ...
I completely forgot about this. The first time I added that line my game crashed. So I disabled it. And the config was still working for world generation settings etc. Now it also works for block properties. Thank you :)
