### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by BedrockLegends** [waylanderou/almost-all-the-ores#9]
![2020-05-22_23 16 09](https://user-images.githubusercontent.com/48525410/82721379-42e1d780-9c82-11ea-93d6-a4645a152e68.png)

Anyway you can add a config option to  hide/remove your Ore blocks from JEI as for like sky packs for example they take up way to much room in JEI

**Comment by waylanderou** [comment]
Update released for both 1.14.4 and 1.15.2.
